/// Lightweight bilingual string table (Russian / English).
///
/// The UI language is also sent to the API as `lang`, so labels coming from
/// Yandex match the language chosen here.
class AppStrings {
  final String lang;
  const AppStrings(this.lang);

  static const supported = ['ru', 'en'];

  String operator [](String key) {
    final table = lang == 'en' ? _en : _ru;
    return table[key] ?? _en[key] ?? key;
  }

  static const Map<String, String> _ru = {
    'app.title': 'AdPocket',
    'tab.dashboard': 'Обзор',
    'tab.reports': 'Отчёты',
    'tab.adunits': 'Блоки',
    'tab.settings': 'Настройки',

    // Onboarding
    'token.title': 'Подключите аккаунт РСЯ',
    'token.subtitle':
        'Вставьте OAuth‑токен API статистики. Токен хранится только на этом устройстве.',
    'token.field': 'OAuth‑токен',
    'token.continue': 'Продолжить',
    'token.howto': 'Где взять токен',
    'token.step1': 'Откройте partner.yandex.ru и войдите в аккаунт.',
    'token.step2': 'На правой панели нажмите кнопку «API».',
    'token.step3': 'Выберите «Получить OAuth‑токен для API статистики».',
    'token.step4': 'Скопируйте токен и вставьте его сюда.',
    'token.open': 'Открыть partner.yandex.ru',
    'token.checking': 'Проверяем токен…',
    'token.invalid':
        'Токен не принят. Проверьте, что скопирован токен API статистики.',
    'token.empty': 'Введите токен',

    // Dashboard
    'dash.title': 'Обзор',
    'dash.today': 'Сегодня',
    'dash.yesterday': 'Вчера',
    'dash.week': 'Эта неделя',
    'dash.last7': 'Последние 7 дней',
    'dash.month': 'Этот месяц',
    'dash.lastMonth': 'Прошлый месяц',
    'dash.days7': '7 дней',
    'dash.days30': '30 дней',
    'dash.vsYesterday': 'к вчера',
    'dash.vsPrev': 'к пред. периоду',
    'dash.vs': 'vs',
    'dash.comparedWith': 'Сравнение с',
    'dash.revenue': 'Доход',
    'dash.shows': 'Показы',
    'dash.clicks': 'Клики',
    'dash.ecpm': 'eCPM',
    'dash.fill': 'Fill rate',
    'dash.ctr': 'CTR',
    'dash.trend': 'Доход за 30 дней',
    'dash.trendShows': 'Показы за 30 дней',
    'dash.topApps': 'Приложения и сайты',
    'dash.updated': 'Обновлено',
    'dash.refresh': 'Обновить',
    'dash.noData': 'Нет данных за этот период',
    'dash.openReport': 'Открыть в отчётах',
    'dash.details': 'Показатели периода',

    // Reports
    'rep.title': 'Отчёты',
    'rep.period': 'Период',
    'rep.type': 'Тип отчёта',
    'rep.typeEmpty': 'Для этого типа отчёта у аккаунта нет показателей.',
    'rep.metrics': 'Показатели',
    'rep.groups': 'Группировки',
    'rep.filters': 'Фильтры',
    'rep.apply': 'Показать',
    'rep.reset': 'Сбросить',
    'rep.selected': 'выбрано',
    'rep.none': 'не выбрано',
    'rep.noFilters': 'без фильтров',
    'rep.results': 'Результаты',
    'rep.totals': 'Итого',
    'rep.rows': 'строк',
    'rep.loadMore': 'Загрузить ещё',
    'rep.table': 'Таблица',
    'rep.chart': 'График',
    'rep.share': 'Поделиться CSV',
    'rep.presets': 'Шаблоны',
    'rep.savePreset': 'Сохранить как шаблон',
    'rep.presetName': 'Название шаблона',
    'rep.save': 'Сохранить',
    'rep.cancel': 'Отмена',
    'rep.delete': 'Удалить',
    'rep.done': 'Готово',
    'rep.needSelection': 'Выберите хотя бы один показатель и одну группировку.',
    'rep.empty': 'По этим условиям данных нет.',
    'rep.error': 'Не удалось загрузить отчёт',
    'rep.retry': 'Повторить',
    'rep.customRange': 'Произвольный период',
    'rep.sortHint': 'Нажмите на заголовок показателя, чтобы отсортировать',
    'rep.addFilter': 'Добавить фильтр',
    'rep.filterField': 'Поле',
    'rep.filterOp': 'Условие',
    'rep.filterValue': 'Значение',
    'rep.filterAdd': 'Добавить',
    'rep.off': 'Выкл.',
    'rep.presetSaved': 'Шаблон сохранён',
    'rep.presetApplied': 'Шаблон применён',
    'rep.loadingFields': 'Загружаем список полей…',
    'rep.fieldsError': 'Не удалось загрузить список полей',
    'rep.tooManyForChart':
        'Для графика выберите группировку по дате или одну группировку',
    'rep.showing': 'Показано',
    'rep.of': 'из',

    // Operators
    'op.eq': 'равно',
    'op.ne': 'не равно',
    'op.like': 'содержит',
    'op.notLike': 'не содержит',
    'op.in': 'один из',
    'op.gt': 'больше',
    'op.lt': 'меньше',
    'op.true': 'да',
    'op.false': 'нет',

    // Ad units
    'ad.title': 'Рекламные блоки',
    'ad.beta': 'бета',
    'ad.intro':
        'Управление блоками мобильных приложений через Inventory API. Нужен отдельный токен с доступом к API рекламного инвентаря.',
    'ad.tokenField': 'Токен Inventory API',
    'ad.connect': 'Подключить',
    'ad.enabled': 'Активные',
    'ad.archived': 'Архив',
    'ad.empty': 'Блоков не найдено',
    'ad.app': 'Приложение',
    'ad.created': 'Создан',
    'ad.strategy': 'Стратегия',
    'ad.strategy.MaxRevenueStrategy': 'Максимальный доход',
    'ad.strategy.MinECpmStrategy': 'Мин. eCPM',
    'ad.strategy.MinCpmVStrategy': 'Мин. CPMV',
    'ad.floor': 'Порог (floor)',
    'ad.caption': 'Название',
    'ad.edit': 'Редактировать',
    'ad.archive': 'Архивировать',
    'ad.archiveConfirm':
        'Архивировать блок? Отменить это через приложение нельзя.',
    'ad.saved': 'Блок обновлён',
    'ad.archivedOk': 'Блок перенесён в архив',
    'ad.notEditable': 'Этот блок нельзя редактировать через API',
    'ad.error': 'Ошибка Inventory API',
    'ad.disconnect': 'Отключить токен',
    'ad.copy': 'ID скопирован',
    'ad.reward': 'Награда',
    'ad.type.banner': 'Баннер',
    'ad.type.interstitial': 'Межстраничный',
    'ad.type.rewarded': 'С вознаграждением',
    'ad.type.native': 'Нативный',
    'ad.type.appopen': 'При открытии',
    'ad.howto': 'Как получить токен Inventory API',
    'ad.step1':
        'Доступ выдаётся по запросу: напишите в поддержку РСЯ (форма или чат в интерфейсе partner.yandex.ru) и попросите доступ к API рекламы в приложениях (API настройки блоков).',
    'ad.step2':
        'После одобрения откройте partner.yandex.ru, на правой панели нажмите значок «API».',
    'ad.step3':
        'Выберите «Получить OAuth‑токен для API настройки блоков» — это отдельный пункт, не токен статистики.',
    'ad.step4':
        'Скопируйте токен и вставьте его сюда. Приложения должны быть уже созданы в интерфейсе — API управляет только блоками внутри них.',
    'ad.openDocs': 'Документация API',
    'ad.openSupport': 'Написать в поддержку',
    'ad.wrongToken':
        'Похоже, это токен API статистики. Для этого раздела нужен токен API настройки блоков.',

    // Settings
    'set.title': 'Настройки',
    'set.account': 'Аккаунт',
    'acc.title': 'Аккаунты',
    'acc.add': 'Добавить аккаунт',
    'acc.label': 'Название (необязательно)',
    'acc.default': 'Аккаунт %d',
    'acc.active': 'Текущий',
    'acc.rename': 'Переименовать',
    'acc.remove': 'Удалить аккаунт',
    'acc.removeConfirm': 'Удалить токен этого аккаунта с устройства?',
    'acc.added': 'Аккаунт добавлен',
    'acc.switchTo': 'Переключить аккаунт',
    'set.token': 'Токен API статистики',
    'set.changeToken': 'Заменить токен',
    'set.logout': 'Выйти',
    'set.logoutConfirm': 'Удалить токен с устройства и выйти?',
    'set.display': 'Отображение',
    'set.language': 'Язык',
    'set.currency': 'Валюта',
    'set.vat': 'Учитывать НДС',
    'set.vatHint': 'Показывать суммы с НДС',
    'set.theme': 'Тема',
    'set.theme.system': 'Как в системе',
    'set.theme.light': 'Светлая',
    'set.theme.dark': 'Тёмная',
    'set.about': 'О приложении',
    'set.version': 'Версия',
    'set.docs': 'Документация API',
    'set.privacy': 'Политика конфиденциальности',
    'set.notOfficial': 'AdPocket — не официальное приложение Яндекса',
    'set.dashboard': 'Открыть partner.yandex.ru',
    'set.clearCache': 'Очистить кэш отчётов',
    'set.cacheCleared': 'Кэш очищен',
    'set.tokenSaved': 'Токен сохранён',
    'set.security': 'Безопасность',
    'set.appLock': 'Блокировка приложения',
    'set.appLockHint':
        'Запрашивать отпечаток, лицо или PIN устройства при открытии',
    'set.appLockUnavailable': 'На устройстве не настроена блокировка экрана',
    'set.secureNote':
        'Токены хранятся в защищённом хранилище системы (Keystore / Keychain)',
    'lock.title': 'Приложение заблокировано',
    'lock.subtitle': 'Подтвердите личность, чтобы открыть статистику',
    'lock.unlock': 'Разблокировать',
    'lock.reason': 'Разблокируйте AdPocket',
    'set.widgets': 'Виджет на главном экране',
    'set.widgetAdd': 'Добавить виджет',
    'set.widgetAddHint':
        'Доход за сегодня, изменение к вчера и тренд за 7 дней',
    'set.widgetRefresh': 'Фоновое обновление',
    'set.widgetRefreshHint':
        'Каждые 30 минут при наличии сети. Выключите, чтобы виджет не обновлялся',
    'set.widgetRefreshNow': 'Обновить сейчас',
    'set.widgetUpdated': 'Виджет обновлён',
    'set.widgetRemoveHint':
        'Чтобы убрать виджет, удерживайте его на главном экране и выберите «Удалить».',
    'set.widgetPinUnsupported':
        'Этот лаунчер не поддерживает добавление виджета из приложения. Удерживайте пустое место на главном экране → Виджеты → AdPocket.',
    'widget.signedOut': 'Откройте приложение и войдите',
    'battery.title': 'Разрешить работу в фоне',
    'notif.section': 'Уведомления',
    'notif.daily': 'Ежедневная сводка',
    'notif.dailyHint': 'Доход за вчера, показы и eCPM',
    'notif.monthly': 'Итоги месяца',
    'notif.monthlyHint': '1‑го числа — доход за прошедший месяц',
    'notif.alerts': 'Оповещения',
    'notif.alertsHint':
        'Падение дохода ниже половины среднего за неделю; нет показов к 12:00 МСК',
    'notif.time': 'Время',
    'notif.iosHint': 'Тексты обновляются при открытии приложения.',
    'notif.androidHint':
        'Тексты обновляются вместе с виджетом (фоновое обновление) и при открытии приложения. Время срабатывания приблизительное.',
    'notif.denied': 'Уведомления запрещены в настройках системы.',
    'notif.test': 'Отправить тестовое уведомление',
    'notif.asOf': 'данные на',
    'notif.dailyTitle': 'AdPocket',
    'notif.monthlyTitle': 'Итоги месяца',
    'notif.dropTitle': 'Доход упал',
    'notif.dropBody': 'Вчера %v — на %p% ниже среднего за неделю (%a).',
    'notif.zeroTitle': 'Сегодня нет показов',
    'notif.zeroBody':
        'К %t по МСК показов ещё нет, вчера было %y. Проверьте блоки.',
    'notif.channelSummary': 'Сводки',
    'notif.channelSummaryDesc': 'Ежедневная и месячная сводка дохода',
    'notif.channelAlerts': 'Оповещения',
    'notif.channelAlertsDesc': 'Падение дохода и отсутствие показов',
    'battery.body':
        'Система ограничивает фоновую работу приложения, поэтому виджет может перестать обновляться. Откроется список оптимизации батареи: найдите AdPocket и выберите «Не оптимизировать». Приложение делает два коротких запроса каждые 30 минут.',
    'battery.allow': 'Разрешить',
    'battery.later': 'Позже',
    'battery.openSettings': 'Открыть настройки приложения',
    'battery.status': 'Фоновая работа',
    'battery.ok': 'Без ограничений',
    'battery.restricted': 'Ограничена системой — виджет может не обновляться',
    'battery.hint.samsung':
        'Samsung: Настройки → Батарея → Ограничения в фоновом режиме → уберите AdPocket из «Спящих» и «Глубокий сон»; в «Сведениях о приложении → Батарея» выберите «Без ограничений».',
    'battery.hint.xiaomi':
        'Xiaomi / Redmi / POCO: Сведения о приложении → Контроль активности → «Без ограничений», и включите «Автозапуск».',
    'battery.hint.huawei':
        'Huawei / Honor: Настройки → Батарея → Запуск приложений → AdPocket → «Управлять вручную» и включите все три пункта.',
    'battery.hint.oppo':
        'OPPO / realme / OnePlus: Сведения о приложении → Батарея → «Разрешить работу в фоне» и включите «Автозапуск».',
    'battery.hint.vivo':
        'vivo / iQOO: Сведения о приложении → Батарея → «Высокое энергопотребление в фоне» и включите «Автозапуск».',
    'widget.offline': 'нет сети',
    'set.widgetIosHint':
        'Удерживайте пустое место на главном экране → «+» → AdPocket. Виджет обновляется сам примерно каждые 30 минут и при каждом открытии приложения.',
    'widget.error': 'ошибка',
    'set.widgetCount': 'На главном экране: %d',
    'set.widgetAlready':
        'Виджет уже на главном экране. Ещё один можно добавить через меню виджетов лаунчера.',

    // Common
    'common.error': 'Ошибка',
    'common.retry': 'Повторить',
    'common.close': 'Закрыть',
    'common.noInternet': 'Нет соединения с сетью',
    'common.unauthorized': 'Токен недействителен. Замените его в настройках.',
    'common.ok': 'ОК',
    'common.all': 'Все',
    'common.search': 'Поиск',
  };

  static const Map<String, String> _en = {
    'app.title': 'AdPocket',
    'tab.dashboard': 'Overview',
    'tab.reports': 'Reports',
    'tab.adunits': 'Ad units',
    'tab.settings': 'Settings',

    'token.title': 'Connect your YAN account',
    'token.subtitle':
        'Paste your Statistics API OAuth token. It is stored only on this device.',
    'token.field': 'OAuth token',
    'token.continue': 'Continue',
    'token.howto': 'Where to get the token',
    'token.step1': 'Open partner.yandex.ru and sign in.',
    'token.step2': 'On the right‑hand panel tap the “API” button.',
    'token.step3': 'Choose “Get OAuth token for the Statistics API”.',
    'token.step4': 'Copy the token and paste it here.',
    'token.open': 'Open partner.yandex.ru',
    'token.checking': 'Checking the token…',
    'token.invalid':
        'Token rejected. Make sure you copied the Statistics API token.',
    'token.empty': 'Enter a token',

    'dash.title': 'Overview',
    'dash.today': 'Today',
    'dash.yesterday': 'Yesterday',
    'dash.week': 'This week',
    'dash.last7': 'Last 7 days',
    'dash.month': 'This month',
    'dash.lastMonth': 'Last month',
    'dash.days7': '7 days',
    'dash.days30': '30 days',
    'dash.vsYesterday': 'vs yesterday',
    'dash.vsPrev': 'vs previous',
    'dash.vs': 'vs',
    'dash.comparedWith': 'Compared with',
    'dash.revenue': 'Revenue',
    'dash.shows': 'Impressions',
    'dash.clicks': 'Clicks',
    'dash.ecpm': 'eCPM',
    'dash.fill': 'Fill rate',
    'dash.ctr': 'CTR',
    'dash.trend': 'Revenue, last 30 days',
    'dash.trendShows': 'Impressions, last 30 days',
    'dash.topApps': 'Apps and sites',
    'dash.updated': 'Updated',
    'dash.refresh': 'Refresh',
    'dash.noData': 'No data for this period',
    'dash.openReport': 'Open in reports',
    'dash.details': 'Period metrics',

    'rep.title': 'Reports',
    'rep.period': 'Period',
    'rep.type': 'Report type',
    'rep.typeEmpty': 'This account has no metrics for this report type.',
    'rep.metrics': 'Metrics',
    'rep.groups': 'Group by',
    'rep.filters': 'Filters',
    'rep.apply': 'Run report',
    'rep.reset': 'Reset',
    'rep.selected': 'selected',
    'rep.none': 'none selected',
    'rep.noFilters': 'no filters',
    'rep.results': 'Results',
    'rep.totals': 'Totals',
    'rep.rows': 'rows',
    'rep.loadMore': 'Load more',
    'rep.table': 'Table',
    'rep.chart': 'Chart',
    'rep.share': 'Share CSV',
    'rep.presets': 'Presets',
    'rep.savePreset': 'Save as preset',
    'rep.presetName': 'Preset name',
    'rep.save': 'Save',
    'rep.cancel': 'Cancel',
    'rep.delete': 'Delete',
    'rep.done': 'Done',
    'rep.needSelection': 'Pick at least one metric and one grouping.',
    'rep.empty': 'No data for these conditions.',
    'rep.error': 'Could not load the report',
    'rep.retry': 'Retry',
    'rep.customRange': 'Custom range',
    'rep.sortHint': 'Tap a metric header to sort',
    'rep.addFilter': 'Add filter',
    'rep.filterField': 'Field',
    'rep.filterOp': 'Condition',
    'rep.filterValue': 'Value',
    'rep.filterAdd': 'Add',
    'rep.off': 'Off',
    'rep.presetSaved': 'Preset saved',
    'rep.presetApplied': 'Preset applied',
    'rep.loadingFields': 'Loading field catalogue…',
    'rep.fieldsError': 'Could not load the field catalogue',
    'rep.tooManyForChart': 'Group by date or by a single field to see a chart',
    'rep.showing': 'Showing',
    'rep.of': 'of',

    'op.eq': 'equals',
    'op.ne': 'not equal',
    'op.like': 'contains',
    'op.notLike': 'does not contain',
    'op.in': 'one of',
    'op.gt': 'greater than',
    'op.lt': 'less than',
    'op.true': 'yes',
    'op.false': 'no',

    'ad.title': 'Ad units',
    'ad.beta': 'beta',
    'ad.intro':
        'Manage mobile app ad units through the Inventory API. It needs a separate token with ad‑inventory access.',
    'ad.tokenField': 'Inventory API token',
    'ad.connect': 'Connect',
    'ad.enabled': 'Active',
    'ad.archived': 'Archived',
    'ad.empty': 'No ad units found',
    'ad.app': 'App',
    'ad.created': 'Created',
    'ad.strategy': 'Strategy',
    'ad.strategy.MaxRevenueStrategy': 'Maximum revenue',
    'ad.strategy.MinECpmStrategy': 'Min eCPM floor',
    'ad.strategy.MinCpmVStrategy': 'Min CPMV floor',
    'ad.floor': 'Floor value',
    'ad.caption': 'Caption',
    'ad.edit': 'Edit',
    'ad.archive': 'Archive',
    'ad.archiveConfirm':
        'Archive this ad unit? This cannot be undone from the app.',
    'ad.saved': 'Ad unit updated',
    'ad.archivedOk': 'Ad unit archived',
    'ad.notEditable': 'This ad unit cannot be edited through the API',
    'ad.error': 'Inventory API error',
    'ad.disconnect': 'Disconnect token',
    'ad.copy': 'ID copied',
    'ad.reward': 'Reward',
    'ad.type.banner': 'Banner',
    'ad.type.interstitial': 'Interstitial',
    'ad.type.rewarded': 'Rewarded',
    'ad.type.native': 'Native',
    'ad.type.appopen': 'App open',
    'ad.howto': 'How to get an Inventory API token',
    'ad.step1':
        'Access is granted on request: contact YAN support (the form or the chat inside partner.yandex.ru) and ask for access to the in‑app ads API (ad unit configuration API).',
    'ad.step2':
        'Once approved, open partner.yandex.ru and tap the “API” icon on the right‑hand panel.',
    'ad.step3':
        'Choose “Get OAuth token for the ad unit configuration API” — a separate item from the statistics token.',
    'ad.step4':
        'Copy the token and paste it here. Apps must already exist in the partner interface; the API only manages ad units inside them.',
    'ad.openDocs': 'API documentation',
    'ad.openSupport': 'Contact support',
    'ad.wrongToken':
        'This looks like the Statistics API token. This section needs the ad unit configuration API token.',

    'set.title': 'Settings',
    'set.account': 'Account',
    'acc.title': 'Accounts',
    'acc.add': 'Add account',
    'acc.label': 'Label (optional)',
    'acc.default': 'Account %d',
    'acc.active': 'Current',
    'acc.rename': 'Rename',
    'acc.remove': 'Remove account',
    'acc.removeConfirm': "Remove this account's token from this device?",
    'acc.added': 'Account added',
    'acc.switchTo': 'Switch account',
    'set.token': 'Statistics API token',
    'set.changeToken': 'Replace token',
    'set.logout': 'Sign out',
    'set.logoutConfirm': 'Remove the token from this device and sign out?',
    'set.display': 'Display',
    'set.language': 'Language',
    'set.currency': 'Currency',
    'set.vat': 'Include VAT',
    'set.vatHint': 'Show amounts including VAT',
    'set.theme': 'Theme',
    'set.theme.system': 'System',
    'set.theme.light': 'Light',
    'set.theme.dark': 'Dark',
    'set.about': 'About',
    'set.version': 'Version',
    'set.docs': 'API documentation',
    'set.privacy': 'Privacy policy',
    'set.notOfficial': 'AdPocket is not an official Yandex application',
    'set.dashboard': 'Open partner.yandex.ru',
    'set.clearCache': 'Clear report cache',
    'set.cacheCleared': 'Cache cleared',
    'set.tokenSaved': 'Token saved',
    'set.security': 'Security',
    'set.appLock': 'App lock',
    'set.appLockHint':
        'Ask for fingerprint, face or device PIN when opening the app',
    'set.appLockUnavailable': 'No screen lock is set up on this device',
    'set.secureNote':
        'Tokens are kept in the system secure store (Keystore / Keychain)',
    'lock.title': 'App is locked',
    'lock.subtitle': 'Confirm it is you to see your statistics',
    'lock.unlock': 'Unlock',
    'lock.reason': 'Unlock AdPocket',
    'set.widgets': 'Home-screen widget',
    'set.widgetAdd': 'Add widget',
    'set.widgetAddHint':
        "Today's revenue, change vs yesterday and a 7-day trend",
    'set.widgetRefresh': 'Background refresh',
    'set.widgetRefreshHint':
        'Every 30 minutes while online. Turn off to stop the widget updating',
    'set.widgetRefreshNow': 'Refresh now',
    'set.widgetUpdated': 'Widget updated',
    'set.widgetRemoveHint':
        'To remove the widget, long-press it on the home screen and choose Remove.',
    'set.widgetPinUnsupported':
        'This launcher cannot add widgets from an app. Long-press an empty spot on the home screen → Widgets → AdPocket.',
    'widget.signedOut': 'Open the app and sign in',
    'battery.title': 'Allow background activity',
    'notif.section': 'Notifications',
    'notif.daily': 'Daily summary',
    'notif.dailyHint': "Yesterday's revenue, impressions and eCPM",
    'notif.monthly': 'Monthly summary',
    'notif.monthlyHint': 'On the 1st — revenue of the month just ended',
    'notif.alerts': 'Alerts',
    'notif.alertsHint':
        'Revenue below half the weekly average; no impressions by 12:00 MSK',
    'notif.time': 'Time',
    'notif.iosHint': 'Texts are refreshed when the app is opened.',
    'notif.androidHint':
        'Texts are refreshed together with the widget (background refresh) and when the app is opened. Delivery time is approximate.',
    'notif.denied': 'Notifications are blocked in system settings.',
    'notif.test': 'Send a test notification',
    'notif.asOf': 'as of',
    'notif.dailyTitle': 'AdPocket',
    'notif.monthlyTitle': 'Month summary',
    'notif.dropTitle': 'Revenue dropped',
    'notif.dropBody': 'Yesterday %v — %p% below the weekly average (%a).',
    'notif.zeroTitle': 'No impressions today',
    'notif.zeroBody':
        'No impressions by %t MSK; yesterday had %y. Check your ad units.',
    'notif.channelSummary': 'Summaries',
    'notif.channelSummaryDesc': 'Daily and monthly revenue summaries',
    'notif.channelAlerts': 'Alerts',
    'notif.channelAlertsDesc': 'Revenue drops and missing impressions',
    'battery.body':
        'The system restricts this app in the background, so the widget may stop updating. The battery-optimisation list will open: find AdPocket and choose "Don\'t optimize". The app makes two short requests every 30 minutes.',
    'battery.allow': 'Allow',
    'battery.later': 'Later',
    'battery.openSettings': 'Open app settings',
    'battery.status': 'Background activity',
    'battery.ok': 'Unrestricted',
    'battery.restricted':
        'Restricted by the system — the widget may not update',
    'battery.hint.samsung':
        'Samsung: Settings → Battery → Background usage limits → remove AdPocket from Sleeping and Deep sleeping apps; in App info → Battery choose Unrestricted.',
    'battery.hint.xiaomi':
        'Xiaomi / Redmi / POCO: App info → Battery saver → No restrictions, and enable Autostart.',
    'battery.hint.huawei':
        'Huawei / Honor: Settings → Battery → App launch → AdPocket → Manage manually, enable all three switches.',
    'battery.hint.oppo':
        'OPPO / realme / OnePlus: App info → Battery → Allow background activity, and enable Auto-launch.',
    'battery.hint.vivo':
        'vivo / iQOO: App info → Battery → High background power consumption, and enable Autostart.',
    'widget.offline': 'offline',
    'set.widgetIosHint':
        'Long-press an empty spot on the home screen → “+” → AdPocket. The widget refreshes itself about every 30 minutes and whenever the app opens.',
    'widget.error': 'error',
    'set.widgetCount': 'On home screen: %d',
    'set.widgetAlready':
        "Widget is already on the home screen. Another one can be added from the launcher's widget picker.",

    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.close': 'Close',
    'common.noInternet': 'No network connection',
    'common.unauthorized': 'The token is invalid. Replace it in Settings.',
    'common.ok': 'OK',
    'common.all': 'All',
    'common.search': 'Search',
  };
}
